#!/bin/bash

config_file="/etc/flatrun.conf"

if [ -f "$config_file" ]; then
    echo sourcing $config_file
    source $config_file 
fi 

cmd=$1
shift 

cmd_id=${aliases[$cmd]}
cmd_name=${cmd_id:-$cmd}

logfile="/tmp/$(short_date)_${cmd}.log"
echo Generating logfile... $logfile   
#flatpak run com.github.dail8859.NotepadNext $* 2>&1  /tmp/NotepadNext_$timestamp.log
flatpak run $cmd_name $* > $logfile 2>&1 & 

exit 0 

