#!/bin/bash
# Check if argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <VM Domain>"
    exit 1
fi

# Set options based on the argument
port=$(virsh -c qemu:///system  domdisplay $1  | sed -rn 's/.*://p')
xml=/tmp/$1.xml 
virsh -c qemu:///system dumpxml $1  > $xml 
shmem=$(xmllint --xpath "string(//shmem/@name)" $xml) 
echo port is:  $port 
echo shmem is:  $shmem

logfile="/tmp/looking-glass_$(short_date).log"
echo "Generating logfile... $logfile"
echo "DBG Win title is supposed to be $1"
looking-glass-client -p $port -f /dev/shm/$shmem  win:title="$1" > $logfile 2>&1 &
echo "Looking Glass PID $!"

